import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from '../styles/home-layout.module.scss';
import Links from "../components/Links";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cam Anderson Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <div className={styles.window}>
          <div className={`${styles.topScreenBar} ${styles.rowFlex} `}>
            <div className={` ${styles.windowControlContainer} ${styles.windowIconRed} `}></div>
            <div className={` ${styles.windowControlContainer} ${styles.windowIconYellow} `}></div>
            <div className={` ${styles.windowControlContainer} ${styles.windowIconGreen} `}></div>
          </div>

          <div className={`${styles.homeContainer} ${styles.rowFlex}`}>
            <div className={styles.iconsPane}>
              <p>icons</p>
            </div>

            <Links />

            {children}
          </div>

          <div className={styles.bottomScreenBar}>
            <div>footer</div>
          </div>

        </div>
      </body>
    </html>
  );
}
