import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "../components/AppProvider";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Cam Anderson Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`antialiased`}
    >
      <head>
        <Script id="theme-init" strategy="beforeInteractive">
          {`
            (function() {
              try {
                var stored = localStorage.getItem('portfolio-theme');
                var validThemes = ['light', 'dark', 'matrix'];
                if (stored && validThemes.indexOf(stored) !== -1) {
                  document.documentElement.setAttribute('data-theme', stored);
                }
              } catch (e) {}
            })();
          `}
        </Script>
        <Script id="show-tags-init" strategy="beforeInteractive">
          {`
              (function() {
                try {
                  var stored = localStorage.getItem('portfolio-show-tags');
                  if (stored === 'true' || stored === 'false') {
                    document.documentElement.setAttribute('data-show-tags', stored);
                  }
                } catch (e) {}
              })();
          `}
        </Script>
      </head>
      <body>
        <AppProvider children={children}/>
      </body>
    </html>
  );
}
